version: '3'

services:
    web:
        image: gonzaflores02/tp-div_313_grupo_floresgonzalo
        ports:
            - "8081:80"
        volumes:
            - ./web/file/:/usr/share/nginx/html/file/
