---
# tasks file for TP_INI
- name: "Rol: TP_INI - Grupo: {{ Nombre_Grupo }}"
  debug:
    msg: "Inicio de tareas dentro del Rol: TP_INI"

- name: "Creo directorio /tmp/Grupo"
  become: yes
  file:
    path: /tmp/Grupo
    state: directory
    owner: vagrant

- name: "Agrego archivo desde template"
  template:
    src: template_01.j2
    dest: /tmp/Grupo/datos.txt
    owner: vagrant
